# Generated by Django 3.0.6 on 2020-05-18 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plannings', '0005_auto_20200518_1217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guestemail',
            old_name='mail',
            new_name='email',
        ),
    ]
