# Generated by Django 3.0.6 on 2020-05-21 06:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('plannings', '0006_auto_20200518_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='planning',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='planning',
            name='last_modification_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
