# Generated by Django 3.0.6 on 2020-05-21 18:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('participations', '0001_initial'),
        ('plannings', '0007_auto_20200521_0859'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['date']},
        ),
        migrations.AddField(
            model_name='event',
            name='participations',
            field=models.ManyToManyField(through='participations.Participation', to=settings.AUTH_USER_MODEL),
        ),
    ]
