# Generated by Django 3.0.6 on 2020-05-22 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plannings', '0008_auto_20200521_2053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='participations',
            new_name='participants',
        ),
    ]
