# Generated by Django 3.0.7 on 2020-06-10 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plannings', '0009_auto_20200522_0910'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guestemail',
            options={'ordering': ['email']},
        ),
        migrations.AlterField(
            model_name='event',
            name='address',
            field=models.CharField(blank=True, max_length=300, verbose_name='adresse'),
        ),
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.TimeField(blank=True, null=True, verbose_name='horaire'),
        ),
        migrations.AlterField(
            model_name='planning',
            name='name',
            field=models.CharField(max_length=200, verbose_name='nom'),
        ),
        migrations.AlterField(
            model_name='planning',
            name='protected',
            field=models.BooleanField(default=False, verbose_name='protégé'),
        ),
    ]
