# Generated by Django 3.0.7 on 2020-06-10 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participations', '0003_auto_20200521_2112'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participation',
            options={'ordering': ['participant__first_name']},
        ),
    ]
